### ISSUE TITLE
Are you ok?

### ISSUE THREAD

**Issue by forkercat** [14zwyan/shell_learning#4]
I am worrying about you

**Comment by ghost** [comment]
This was unexpected. lol I'm okay. Why do you ask?

If it's because I've not contributed to this repository in a little while, that's because I've got a lot of other projects and other people's repositories to which I often contribute. But this repository is most certainly on my list, and it always gets pulled in locally, in-case you make any changes. :)

**Comment by ZhiweiYan-96** [comment]
> This was unexpected. lol I'm okay. Why do you ask?
> 
> If it's because I've not contributed to this repository in a little while, that's because I've got a lot of other projects and other people's repositories to which I often contribute. But this repository is most certainly on my list, and it always gets pulled in locally, in-case you make any changes. :)

emm He is a friend of mine. This guy just want to make some joke lol Just ignore him lol lol : )

**Comment by ghost** [comment]
How goes the shell learning? Hope you've not given it up! I'm about to contribute some more information.

**Comment by forkercat** [comment]
fight on guys!

**Comment by ZhiweiYan-96** [comment]
> How goes the shell learning? Hope you've not given it up! I'm about to contribute some more information.

I'm still work on shell learning. But i also have some other works to do. lol  So the progress may no be such quick.
